### ISSUE TITLE
neovim has a new URL

### ISSUE THREAD

**Issue by joe-sharp** [bpierre/switch-to-vim-for-good#1]
Thanks for the lovely guide! I am well on my way to being proficient in vim. 😄 

I wanted to check out what neovim was all about and found the URL out-of-date. Looks like the project has moved to https://neovim.io/

**Comment by bpierre** [comment]
@joe-sharp Thank you! It’s good to know that this guide is useful :hugs: 

I updated the link :pray:  https://github.com/bpierre/switch-to-vim-for-good/commit/c20a62003a23825cdc8ff232c9357e92a253a3db.  Good luck in your vim journey, it never really ends :smile:
